/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fim_kinematik_mhe_generator_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

#ifndef CASADI_PRINTF
#define CASADI_PRINTF printf
#ifndef CASADI_SNPRINTF
#define CASADI_SNPRINTF snprintf
#endif

#endif

static const casadi_int casadi_s0[3] = {1, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {1, 2, 1};

/* step_kinematik_mhe:(x,theta[2],u[2])->(x_next,Jx,Jtheta[1x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12;
  a00=arg[0]? arg[0][0] : 0;
  a01=3.3333333333333335e-03;
  a02=arg[2]? arg[2][0] : 0;
  a03=arg[1]? arg[1][0] : 0;
  a04=arg[2]? arg[2][1] : 0;
  a05=(a03*a04);
  a06=arg[1]? arg[1][1] : 0;
  a05=(a05+a06);
  a07=tan(a05);
  a07=(a02*a07);
  a08=2.6499999999999999e+00;
  a07=(a07/a08);
  a09=2.;
  a10=(a03*a04);
  a10=(a10+a06);
  a11=tan(a10);
  a11=(a02*a11);
  a11=(a11/a08);
  a11=(a09*a11);
  a07=(a07+a11);
  a11=(a03*a04);
  a11=(a11+a06);
  a12=tan(a11);
  a12=(a02*a12);
  a12=(a12/a08);
  a12=(a09*a12);
  a07=(a07+a12);
  a03=(a03*a04);
  a03=(a03+a06);
  a06=tan(a03);
  a06=(a02*a06);
  a06=(a06/a08);
  a07=(a07+a06);
  a07=(a01*a07);
  a00=(a00+a07);
  if (res[0]!=0) res[0][0]=a00;
  a00=1.;
  if (res[1]!=0) res[1][0]=a00;
  a00=3.7735849056603776e-01;
  a05=cos(a05);
  a05=casadi_sq(a05);
  a07=(a04/a05);
  a07=(a02*a07);
  a07=(a00*a07);
  a10=cos(a10);
  a10=casadi_sq(a10);
  a06=(a04/a10);
  a06=(a02*a06);
  a06=(a00*a06);
  a06=(a09*a06);
  a07=(a07+a06);
  a11=cos(a11);
  a11=casadi_sq(a11);
  a06=(a04/a11);
  a06=(a02*a06);
  a06=(a00*a06);
  a06=(a09*a06);
  a07=(a07+a06);
  a03=cos(a03);
  a03=casadi_sq(a03);
  a04=(a04/a03);
  a04=(a02*a04);
  a04=(a00*a04);
  a07=(a07+a04);
  a07=(a01*a07);
  if (res[2]!=0) res[2][0]=a07;
  a05=(a02/a05);
  a05=(a00*a05);
  a10=(a02/a10);
  a10=(a00*a10);
  a10=(a09*a10);
  a05=(a05+a10);
  a11=(a02/a11);
  a11=(a00*a11);
  a09=(a09*a11);
  a05=(a05+a09);
  a02=(a02/a03);
  a00=(a00*a02);
  a05=(a05+a00);
  a01=(a01*a05);
  if (res[2]!=0) res[2][1]=a01;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int step_kinematik_mhe(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int step_kinematik_mhe_alloc_mem(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int step_kinematik_mhe_init_mem(int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void step_kinematik_mhe_free_mem(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT int step_kinematik_mhe_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void step_kinematik_mhe_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void step_kinematik_mhe_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void step_kinematik_mhe_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int step_kinematik_mhe_n_in(void) { return 3;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int step_kinematik_mhe_n_out(void) { return 3;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real step_kinematik_mhe_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* step_kinematik_mhe_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "theta";
    case 2: return "u";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* step_kinematik_mhe_name_out(casadi_int i) {
  switch (i) {
    case 0: return "x_next";
    case 1: return "Jx";
    case 2: return "Jtheta";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* step_kinematik_mhe_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* step_kinematik_mhe_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int step_kinematik_mhe_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int step_kinematik_mhe_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

casadi_int main_step_kinematik_mhe(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[22];
  const casadi_real* arg[3];
  casadi_real* res[3];
  arg[0] = w+0;
  arg[1] = w+1;
  arg[2] = w+3;
  res[0] = w+5;
  res[1] = w+6;
  res[2] = w+7;
  a = w;
  for (j=0; j<5; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = step_kinematik_mhe(arg, res, iw, w+9, 0);
  if (flag) return flag;
  r = w+5;
  for (j=0; j<4; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "step_kinematik_mhe")==0) {
    return main_step_kinematik_mhe(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'step_kinematik_mhe'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
