/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int step_kinematik_mhe(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int step_kinematik_mhe_alloc_mem(void);
extern "C" int step_kinematik_mhe_init_mem(int mem);
extern "C" void step_kinematik_mhe_free_mem(int mem);
extern "C" int step_kinematik_mhe_checkout(void);
extern "C" void step_kinematik_mhe_release(int mem);
extern "C" void step_kinematik_mhe_incref(void);
extern "C" void step_kinematik_mhe_decref(void);
extern "C" casadi_int step_kinematik_mhe_n_in(void);
extern "C" casadi_int step_kinematik_mhe_n_out(void);
extern "C" casadi_real step_kinematik_mhe_default_in(casadi_int i);
extern "C" const char* step_kinematik_mhe_name_in(casadi_int i);
extern "C" const char* step_kinematik_mhe_name_out(casadi_int i);
extern "C" const casadi_int* step_kinematik_mhe_sparsity_in(casadi_int i);
extern "C" const casadi_int* step_kinematik_mhe_sparsity_out(casadi_int i);
extern "C" int step_kinematik_mhe_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int step_kinematik_mhe_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define step_kinematik_mhe_SZ_ARG 3
#define step_kinematik_mhe_SZ_RES 3
#define step_kinematik_mhe_SZ_IW 0
#define step_kinematik_mhe_SZ_W 0
