/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematik_mpc_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {6, 6, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};

/* kinematik_mpc_expl_vde_forw:(i0[6],i1[6x6],i2[6],i3,i4[4])->(o0[6],o1[6x6],o2[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18;
  a00=arg[0]? arg[0][1] : 0;
  a01=sin(a00);
  if (res[0]!=0) res[0][0]=a01;
  a02=arg[4]? arg[4][0] : 0;
  a03=arg[0]? arg[0][2] : 0;
  a04=arg[4]? arg[4][2] : 0;
  a05=9.9999999999999995e-07;
  a04=casadi_fmax(a04,a05);
  a05=arg[0]? arg[0][5] : 0;
  a06=(a04*a05);
  a06=(a03-a06);
  a07=arg[4]? arg[4][3] : 0;
  a06=(a06+a07);
  a07=tan(a06);
  a07=(a02*a07);
  a08=2.6499999999999999e+00;
  a07=(a07/a08);
  a08=arg[4]? arg[4][1] : 0;
  a09=(a02*a08);
  a00=cos(a00);
  a10=(a09*a00);
  a11=1.;
  a12=arg[0]? arg[0][0] : 0;
  a12=(a08*a12);
  a12=(a12*a02);
  a12=(a11-a12);
  a10=(a10/a12);
  a07=(a07-a10);
  if (res[0]!=0) res[0][1]=a07;
  a07=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][2]=a07;
  a07=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a07;
  if (res[0]!=0) res[0][4]=a05;
  a07=12.;
  a13=casadi_sq(a04);
  a07=(a07/a13);
  a03=(a07*a03);
  a13=arg[0]? arg[0][4] : 0;
  a13=(a07*a13);
  a14=6.;
  a14=(a14/a04);
  a05=(a14*a05);
  a13=(a13+a05);
  a03=(a03-a13);
  if (res[0]!=0) res[0][5]=a03;
  a03=arg[1]? arg[1][1] : 0;
  a13=(a00*a03);
  if (res[1]!=0) res[1][0]=a13;
  a13=3.7735849056603776e-01;
  a05=arg[1]? arg[1][2] : 0;
  a15=arg[1]? arg[1][5] : 0;
  a16=(a04*a15);
  a16=(a05-a16);
  a06=cos(a06);
  a06=casadi_sq(a06);
  a16=(a16/a06);
  a16=(a02*a16);
  a16=(a13*a16);
  a10=(a10/a12);
  a17=arg[1]? arg[1][0] : 0;
  a17=(a08*a17);
  a17=(a02*a17);
  a17=(a10*a17);
  a03=(a01*a03);
  a03=(a09*a03);
  a03=(a03/a12);
  a17=(a17-a03);
  a16=(a16-a17);
  if (res[1]!=0) res[1][1]=a16;
  a16=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][2]=a16;
  a16=0.;
  if (res[1]!=0) res[1][3]=a16;
  if (res[1]!=0) res[1][4]=a15;
  a05=(a07*a05);
  a17=arg[1]? arg[1][4] : 0;
  a17=(a07*a17);
  a15=(a14*a15);
  a17=(a17+a15);
  a05=(a05-a17);
  if (res[1]!=0) res[1][5]=a05;
  a05=arg[1]? arg[1][7] : 0;
  a17=(a00*a05);
  if (res[1]!=0) res[1][6]=a17;
  a17=arg[1]? arg[1][8] : 0;
  a15=arg[1]? arg[1][11] : 0;
  a03=(a04*a15);
  a03=(a17-a03);
  a03=(a03/a06);
  a03=(a02*a03);
  a03=(a13*a03);
  a18=arg[1]? arg[1][6] : 0;
  a18=(a08*a18);
  a18=(a02*a18);
  a18=(a10*a18);
  a05=(a01*a05);
  a05=(a09*a05);
  a05=(a05/a12);
  a18=(a18-a05);
  a03=(a03-a18);
  if (res[1]!=0) res[1][7]=a03;
  a03=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][8]=a03;
  if (res[1]!=0) res[1][9]=a16;
  if (res[1]!=0) res[1][10]=a15;
  a17=(a07*a17);
  a03=arg[1]? arg[1][10] : 0;
  a03=(a07*a03);
  a15=(a14*a15);
  a03=(a03+a15);
  a17=(a17-a03);
  if (res[1]!=0) res[1][11]=a17;
  a17=arg[1]? arg[1][13] : 0;
  a03=(a00*a17);
  if (res[1]!=0) res[1][12]=a03;
  a03=arg[1]? arg[1][14] : 0;
  a15=arg[1]? arg[1][17] : 0;
  a18=(a04*a15);
  a18=(a03-a18);
  a18=(a18/a06);
  a18=(a02*a18);
  a18=(a13*a18);
  a05=arg[1]? arg[1][12] : 0;
  a05=(a08*a05);
  a05=(a02*a05);
  a05=(a10*a05);
  a17=(a01*a17);
  a17=(a09*a17);
  a17=(a17/a12);
  a05=(a05-a17);
  a18=(a18-a05);
  if (res[1]!=0) res[1][13]=a18;
  a18=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][14]=a18;
  if (res[1]!=0) res[1][15]=a16;
  if (res[1]!=0) res[1][16]=a15;
  a03=(a07*a03);
  a18=arg[1]? arg[1][16] : 0;
  a18=(a07*a18);
  a15=(a14*a15);
  a18=(a18+a15);
  a03=(a03-a18);
  if (res[1]!=0) res[1][17]=a03;
  a03=arg[1]? arg[1][19] : 0;
  a18=(a00*a03);
  if (res[1]!=0) res[1][18]=a18;
  a18=arg[1]? arg[1][20] : 0;
  a15=arg[1]? arg[1][23] : 0;
  a05=(a04*a15);
  a05=(a18-a05);
  a05=(a05/a06);
  a05=(a02*a05);
  a05=(a13*a05);
  a17=arg[1]? arg[1][18] : 0;
  a17=(a08*a17);
  a17=(a02*a17);
  a17=(a10*a17);
  a03=(a01*a03);
  a03=(a09*a03);
  a03=(a03/a12);
  a17=(a17-a03);
  a05=(a05-a17);
  if (res[1]!=0) res[1][19]=a05;
  a05=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][20]=a05;
  if (res[1]!=0) res[1][21]=a16;
  if (res[1]!=0) res[1][22]=a15;
  a18=(a07*a18);
  a05=arg[1]? arg[1][22] : 0;
  a05=(a07*a05);
  a15=(a14*a15);
  a05=(a05+a15);
  a18=(a18-a05);
  if (res[1]!=0) res[1][23]=a18;
  a18=arg[1]? arg[1][25] : 0;
  a05=(a00*a18);
  if (res[1]!=0) res[1][24]=a05;
  a05=arg[1]? arg[1][26] : 0;
  a15=arg[1]? arg[1][29] : 0;
  a17=(a04*a15);
  a17=(a05-a17);
  a17=(a17/a06);
  a17=(a02*a17);
  a17=(a13*a17);
  a03=arg[1]? arg[1][24] : 0;
  a03=(a08*a03);
  a03=(a02*a03);
  a03=(a10*a03);
  a18=(a01*a18);
  a18=(a09*a18);
  a18=(a18/a12);
  a03=(a03-a18);
  a17=(a17-a03);
  if (res[1]!=0) res[1][25]=a17;
  a17=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][26]=a17;
  if (res[1]!=0) res[1][27]=a16;
  if (res[1]!=0) res[1][28]=a15;
  a05=(a07*a05);
  a17=arg[1]? arg[1][28] : 0;
  a17=(a07*a17);
  a15=(a14*a15);
  a17=(a17+a15);
  a05=(a05-a17);
  if (res[1]!=0) res[1][29]=a05;
  a05=arg[1]? arg[1][31] : 0;
  a17=(a00*a05);
  if (res[1]!=0) res[1][30]=a17;
  a17=arg[1]? arg[1][32] : 0;
  a15=arg[1]? arg[1][35] : 0;
  a03=(a04*a15);
  a03=(a17-a03);
  a03=(a03/a06);
  a03=(a02*a03);
  a03=(a13*a03);
  a18=arg[1]? arg[1][30] : 0;
  a18=(a08*a18);
  a18=(a02*a18);
  a18=(a10*a18);
  a05=(a01*a05);
  a05=(a09*a05);
  a05=(a05/a12);
  a18=(a18-a05);
  a03=(a03-a18);
  if (res[1]!=0) res[1][31]=a03;
  a03=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][32]=a03;
  if (res[1]!=0) res[1][33]=a16;
  if (res[1]!=0) res[1][34]=a15;
  a17=(a07*a17);
  a16=arg[1]? arg[1][34] : 0;
  a16=(a07*a16);
  a15=(a14*a15);
  a16=(a16+a15);
  a17=(a17-a16);
  if (res[1]!=0) res[1][35]=a17;
  a17=arg[2]? arg[2][1] : 0;
  a00=(a00*a17);
  if (res[2]!=0) res[2][0]=a00;
  a00=arg[2]? arg[2][2] : 0;
  a16=arg[2]? arg[2][5] : 0;
  a04=(a04*a16);
  a04=(a00-a04);
  a04=(a04/a06);
  a04=(a02*a04);
  a13=(a13*a04);
  a04=arg[2]? arg[2][0] : 0;
  a08=(a08*a04);
  a02=(a02*a08);
  a10=(a10*a02);
  a01=(a01*a17);
  a09=(a09*a01);
  a09=(a09/a12);
  a10=(a10-a09);
  a13=(a13-a10);
  if (res[2]!=0) res[2][1]=a13;
  a13=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][2]=a13;
  if (res[2]!=0) res[2][3]=a11;
  if (res[2]!=0) res[2][4]=a16;
  a00=(a07*a00);
  a11=arg[2]? arg[2][4] : 0;
  a07=(a07*a11);
  a14=(a14*a16);
  a07=(a07+a14);
  a00=(a00-a07);
  if (res[2]!=0) res[2][5]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematik_mpc_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematik_mpc_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematik_mpc_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematik_mpc_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematik_mpc_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int kinematik_mpc_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real kinematik_mpc_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematik_mpc_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematik_mpc_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematik_mpc_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematik_mpc_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
