/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) kinematik_mpc_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {7, 1, 1};

/* kinematik_mpc_cost_ext_cost_0_fun_jac:(i0[6],i1,i2[0],i3[4])->(o0,o1[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19;
  a00=1.4239943040227840e+03;
  a01=arg[0]? arg[0][0] : 0;
  a00=(a00*a01);
  a01=(a00*a01);
  a02=4.6746975436265495e+02;
  a03=arg[0]? arg[0][1] : 0;
  a02=(a02*a03);
  a03=(a02*a03);
  a01=(a01+a03);
  a03=4.0000000000000008e-02;
  a04=arg[0]? arg[0][2] : 0;
  a05=2.6499999999999999e+00;
  a06=arg[3]? arg[3][1] : 0;
  a06=(a05*a06);
  a06=atan(a06);
  a06=(a04-a06);
  a03=(a03*a06);
  a06=(a03*a06);
  a01=(a01+a06);
  a06=arg[1]? arg[1][0] : 0;
  a07=casadi_sq(a06);
  a01=(a01+a07);
  a07=400.;
  a08=arg[0]? arg[0][3] : 0;
  a07=(a07*a08);
  a09=(a07*a08);
  a01=(a01+a09);
  a09=4.;
  a10=0.;
  a11=arg[3]? arg[3][0] : 0;
  a11=casadi_sq(a11);
  a08=(a11*a08);
  a08=(a08/a05);
  a12=casadi_sq(a08);
  a13=1.0000000000000000e-08;
  a12=(a12+a13);
  a12=sqrt(a12);
  a14=2.;
  a14=(a12-a14);
  a15=casadi_fmax(a10,a14);
  a09=(a09*a15);
  a15=(a09*a15);
  a01=(a01+a15);
  a15=100000000.;
  a16=5.;
  a17=(a12-a16);
  a18=casadi_fmax(a10,a17);
  a19=(a15*a18);
  a18=(a19*a18);
  a01=(a01+a18);
  a04=(a11*a04);
  a04=(a04/a05);
  a05=casadi_sq(a04);
  a05=(a05+a13);
  a05=sqrt(a05);
  a16=(a05-a16);
  a13=casadi_fmax(a10,a16);
  a15=(a15*a13);
  a13=(a15*a13);
  a01=(a01+a13);
  if (res[0]!=0) res[0][0]=a01;
  a06=(a06+a06);
  if (res[1]!=0) res[1][0]=a06;
  a00=(a00+a00);
  if (res[1]!=0) res[1][1]=a00;
  a02=(a02+a02);
  if (res[1]!=0) res[1][2]=a02;
  a02=3.7735849056603776e-01;
  a04=(a04+a04);
  a00=(a10<=a16);
  a16=(a16<=a10);
  a16=(a16+a00);
  a00=(a00/a16);
  a15=(a15+a15);
  a00=(a00*a15);
  a05=(a05+a05);
  a00=(a00/a05);
  a04=(a04*a00);
  a04=(a02*a04);
  a04=(a11*a04);
  a03=(a03+a03);
  a04=(a04+a03);
  if (res[1]!=0) res[1][3]=a04;
  a08=(a08+a08);
  a04=(a10<=a17);
  a17=(a17<=a10);
  a17=(a17+a04);
  a04=(a04/a17);
  a19=(a19+a19);
  a04=(a04*a19);
  a12=(a12+a12);
  a04=(a04/a12);
  a04=(a08*a04);
  a19=(a10<=a14);
  a14=(a14<=a10);
  a14=(a14+a19);
  a19=(a19/a14);
  a09=(a09+a09);
  a19=(a19*a09);
  a19=(a19/a12);
  a08=(a08*a19);
  a04=(a04+a08);
  a02=(a02*a04);
  a11=(a11*a02);
  a11=(a11+a07);
  a11=(a11+a07);
  if (res[1]!=0) res[1][4]=a11;
  if (res[1]!=0) res[1][5]=a10;
  if (res[1]!=0) res[1][6]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematik_mpc_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void kinematik_mpc_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kinematik_mpc_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void kinematik_mpc_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kinematik_mpc_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kinematik_mpc_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real kinematik_mpc_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematik_mpc_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* kinematik_mpc_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematik_mpc_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* kinematik_mpc_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int kinematik_mpc_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
